// Build script - emits two artifacts from one source tree:
//
//   1. dist/batchd.user.js        - Tampermonkey userscript
//   2. dist/extension/            - Chrome extension folder containing:
//        content.js               - the bundled content script
//        manifest.json            - copied from extension/manifest.json
//        icons/icon-*.png         - copied from extension/icons/
//
// ESM `export` syntax is rewritten to global namespace assignments so the
// concatenated files run as classic scripts (no module loader). Each build
// uses a different ORDER array: the seven logic modules (yield, pacing,
// persist, failures, selectors, run, panel) are shared; the storage
// adapter and entry point differ per target. See ADR 0004 in docs/adr/.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SHARED_MODULES = [
  'yield.js',
  'pacing.js',
  'persist.js',
  'failures.js',
  'selectors.js',
  'run.js',
  'panel.js',
];

export const TM_ENTRY = 'batchd.user.js';
export const CHROME_ENTRY = 'content.js';

// Both bundles share the seven logic modules, the matching storage
// adapter, and `entry.js` (the `bootstrapBatchd` helper). Only the
// last file in the order differs: `batchd.user.js` for Tampermonkey,
// `content.js` for the Chrome extension. See ADR 0004 in docs/adr/.
const TM_ORDER = [
  'storage.gm.js',
  'entry.js',
  ...SHARED_MODULES,
  TM_ENTRY,
];

const CHROME_ORDER = [
  'storage.chrome.js',
  'entry.js',
  ...SHARED_MODULES,
  CHROME_ENTRY,
];

function sourcePath(filename) {
  return `src/${filename}`;
}

// Repo identity - hardcoded so forking the project is a deliberate edit
// here, not a hunt through package.json. If Batchd ever moves, change
// this block once and the banner follows.
const HOMEPAGE       = 'https://github.com/11sid11/Batchd';
const SUPPORT_URL    = `${HOMEPAGE}/issues`;
const RELEASE_URL    = `${HOMEPAGE}/releases/latest/download/batchd.user.js`;
const ICON_URL       = 'https://raw.githubusercontent.com/11sid11/Batchd/master/assets/logo.svg';
const AUTHOR         = '11sid11';
const LICENSE        = 'MIT';
const DEFAULT_DESC   = 'Bulk-delete your X.com likes and replies.';

// Renders the Tampermonkey ==UserScript== metadata block that sits at the top
// of the built userscript. Exported so tests can assert on the exact fields
// without running a build.
//
// Strategy B for auto-update: @updateURL and @downloadURL both point at the
// GitHub release "latest" download. The release process already uploads
// dist/batchd.user.js as a release asset, so the always-current asset lives
// at that URL. Tampermonkey follows the 302 -> S3 redirect transparently.
// No need to commit dist/ to the repo.
export function renderBanner(pkg) {
  const version     = pkg.version;
  const description = pkg.description || DEFAULT_DESC;

  return `// ==UserScript==
// @name         Batchd
// @namespace    batchd
// @version      ${version}
// @description  ${description}
// @author       ${AUTHOR}
// @license      ${LICENSE}
// @homepage     ${HOMEPAGE}
// @supportURL   ${SUPPORT_URL}
// @icon         ${ICON_URL}
// @updateURL    ${RELEASE_URL}
// @downloadURL  ${RELEASE_URL}
// @match        https://x.com/*
// @match        https://twitter.com/*
// @grant        GM_getValue
// @grant        GM_setValue
// @run-at       document-end
// ==/UserScript==

`;
}

function rewriteEsm(src, filename) {
  // 1. `export function NAME(...)` -> `function NAME(...)` plus `Batchd.NAME = NAME`
  // 2. `export const NAME = ...`  -> `const NAME = ...`
  // 3. `import { X, Y } from './foo.js'` -> `const { X, Y } = Batchd;`
  // 4. `export { X, Y };` -> `Batchd.X = X; Batchd.Y = Y;`
  // 5. `export default X;` -> `Batchd.default = X;`

  let out = src;

  out = out.replace(
    /^import\s*\{\s*([^}]+)\s*\}\s*from\s*['"][^'"]+['"];?\s*$/gm,
    (_, names) => `const { ${names.trim()} } = Batchd;`
  );

  const exportedFns = [];
  out = out.replace(/^export\s+(async\s+)?function\s+(\w+)/gm, (_, asyncKw, name) => {
    exportedFns.push(name);
    return `${asyncKw || ''}function ${name}`;
  });

  if (exportedFns.length > 0) {
    out += '\n' + exportedFns.map((n) => `Batchd.${n} = ${n};`).join('\n') + '\n';
  }

  out = out.replace(/^export\s+const\s+/gm, 'const ');

  out = out.replace(/^export\s*\{\s*([^}]+)\s*\};?\s*$/gm, (_, list) =>
    list.split(',').map((s) => {
      const name = s.trim().split(/\s+as\s+/)[0];
      return `Batchd.${name} = ${name};`;
    }).join('\n')
  );

  out = out.replace(/^export\s+default\s+/gm, 'Batchd.default = ');

  return out;
}

async function buildOne(order, banner, outFile) {
  const parts = [];

  // Outer IIFE - declares the shared `Batchd` namespace once. Each module is
  // then wrapped in its OWN inner IIFE so local bindings (function
  // declarations, `const` aliases) don't leak into other modules' scopes.
  parts.push('// <auto-generated by scripts/build.js - do not edit>\n');
  parts.push('(function () {\n');
  parts.push('  "use strict";\n');
  parts.push('  const Batchd = {};\n');
  parts.push('  const globalThis = window;\n');
  parts.push('  globalThis.Batchd = Batchd;\n\n');

  for (const filename of order) {
    const src = await readFile(sourcePath(filename), 'utf8');
    const rewritten = rewriteEsm(src, filename);

    // For the Tampermonkey entry: strip the @grant/@match header block -
    // the build script writes its own header at the top of the bundle.
    // The Chrome entry point has no such block, so the regex is a no-op.
    const cleaned = filename === TM_ENTRY
      ? rewritten.replace(/^\/\/ ==UserScript==[\s\S]*?\/\/ ==\/UserScript==\s*/m, '')
      : rewritten;

    parts.push(`  // ---- ${sourcePath(filename)} ----\n`);
    parts.push('  (function () {\n');
    parts.push(cleaned.replace(/^/gm, '    '));
    parts.push('\n  })();\n\n');
  }

  parts.push('})();\n');

  const outDir = outFile.substring(0, outFile.lastIndexOf('/'));
  if (!existsSync(outDir)) await mkdir(outDir, { recursive: true });
  const out = banner + parts.join('');
  await writeFile(outFile, out);
  console.log(`built ${outFile} (${out.length} bytes)`);
}

async function buildUserscript() {
  const pkg = JSON.parse(await readFile('package.json', 'utf8'));
  await buildOne(TM_ORDER, renderBanner(pkg), 'dist/batchd.user.js');
}

async function buildExtension() {
  // The Chrome content script has no banner - manifest.json supplies the
  // metadata (name, version, description) to Chrome.
  await buildOne(CHROME_ORDER, '', 'dist/extension/content.js');

  // Copy the manifest and the four icon PNGs so the dist/extension/
  // folder is a complete, loadable extension.
  if (!existsSync('dist/extension/icons')) {
    await mkdir('dist/extension/icons', { recursive: true });
  }
  const manifest = await readFile('extension/manifest.json', 'utf8');
  await writeFile('dist/extension/manifest.json', manifest);
  for (const size of [16, 32, 48, 128]) {
    const bytes = await readFile(`extension/icons/icon-${size}.png`);
    await writeFile(`dist/extension/icons/icon-${size}.png`, bytes);
  }
  console.log('copied manifest.json and icons/ to dist/extension/');
}

async function build(target) {
  if (!target || target === 'all') {
    await buildUserscript();
    await buildExtension();
  } else if (target === 'userscript') {
    await buildUserscript();
  } else if (target === 'extension') {
    await buildExtension();
  } else {
    throw new Error(
      `Unknown build target: ${target} (expected userscript, extension, or all)`,
    );
  }
}

// Only run the build when this file is the entry point (e.g.
// `node scripts/build.js` or `npm run build`). Imports from tests must
// NOT trigger a build - tests want to call renderBanner() in isolation
// without side effects.
const isMain = process.argv[1] && (
  fileURLToPath(import.meta.url) === process.argv[1] ||
  process.argv[1].endsWith('scripts/build.js') ||
  process.argv[1].endsWith('scripts\\build.js')
);

if (isMain) {
  build(process.argv[2]).catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
