// Build script — concatenates src/*.js into a single distributable
// userscript file at dist/batchd.user.js.
//
// ESM `export` syntax is rewritten to global namespace assignments so the
// concatenated file runs as a classic Tampermonkey script (no module loader).
//
// Order matters: modules are concatenated in dependency order, with the
// entry point (batchd.user.js) last. Each module exposes its public
// surface via globalThis.Batchd.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';

const ORDER = [
  'pacing.js',
  'persist.js',
  'failures.js',
  'selectors.js',
  'run.js',
  'panel.js',
  'batchd.user.js',     // entry point — last
];

const OUT_DIR = 'dist';
const OUT_FILE = `${OUT_DIR}/batchd.user.js`;

function rewriteEsm(src, filename) {
  // 1. `export function NAME(...)` -> `Batchd.NAME = function NAME(...)`
  // 2. `export const NAME = ...`  -> `Batchd.NAME = ...`
  // 3. `import { X, Y } from './foo.js'` -> `const { X, Y } = Batchd;`
  // 4. `export { X, Y };` -> `Batchd.X = X; Batchd.Y = Y;`
  // 5. `export default X;` -> `Batchd.default = X;`

  let out = src;

  // Hoist imports to a single Batchd-destructure
  out = out.replace(
    /^import\s*\{\s*([^}]+)\s*\}\s*from\s*['"][^'"]+['"];?\s*$/gm,
    (_, names) => `const { ${names.trim()} } = Batchd;`
  );

  // export function NAME  /  export async function NAME
  out = out.replace(/^export\s+(async\s+)?function\s+(\w+)/gm, 'Batchd.$2 = $1function $2');

  // export const NAME
  out = out.replace(/^export\s+const\s+(\w+)\s*=/gm, 'Batchd.$1 =');

  // export { a, b, c };
  out = out.replace(/^export\s*\{\s*([^}]+)\s*\};?\s*$/gm, (_, list) =>
    list.split(',').map((s) => {
      const name = s.trim().split(/\s+as\s+/)[0];
      return `Batchd.${name} = ${name};`;
    }).join('\n')
  );

  // export default X
  out = out.replace(/^export\s+default\s+/gm, 'Batchd.default = ');

  return out;
}

async function build() {
  const parts = [];

  // IIFE opener that creates the Batchd namespace
  parts.push('// <auto-generated by scripts/build.js — do not edit>\n');
  parts.push('(function () {\n');
  parts.push('  "use strict";\n');
  parts.push('  const Batchd = {};\n');
  parts.push('  const globalThis = window;\n');
  parts.push('  globalThis.Batchd = Batchd;\n\n');

  for (const filename of ORDER) {
    const src = await readFile(`src/${filename}`, 'utf8');
    const rewritten = rewriteEsm(src, filename);

    // For the entry point: strip the @grant/@match header block — the build
    // script writes its own header at the top of the bundle.
    const cleaned = filename === 'batchd.user.js'
      ? rewritten.replace(/^\/\/ ==UserScript==[\s\S]*?\/\/ ==\/UserScript==\s*/, '')
      : rewritten;

    parts.push(`  // ---- src/${filename} ----\n`);
    parts.push(cleaned);
    parts.push('\n\n');
  }

  parts.push('})();\n');

  if (!existsSync(OUT_DIR)) await mkdir(OUT_DIR, { recursive: true });
  const banner = `// ==UserScript==
// @name         Batchd
// @namespace    batchd
// @version      ${(await readFile('package.json', 'utf8')).match(/"version":\s*"([^"]+)"/)[1]}
// @description  Bulk-delete your X.com reposts and likes.
// @match        https://x.com/*
// @match        https://twitter.com/*
// @grant        GM_getValue
// @grant        GM_setValue
// @run-at       document-end
// ==/UserScript==

`;
  await writeFile(OUT_FILE, banner + parts.join(''));
  console.log(`built ${OUT_FILE} (${(banner + parts.join('')).length} bytes)`);
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});
